jobs:
  - job: ubuntu1604
    pool:
      vmImage: 'Ubuntu-16.04'
    displayName: 'Ubuntu 16.04 x86-64'
    steps:
    - script: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update -y
        sudo apt-get install -y libglfw3-dev python2.7-dev libpng16-dev libopenal-dev libluajit-5.1-dev libserialport-dev libsndfile1-dev
        sudo apt-get install -y gcc-8 g++-8
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
        cd ref
        git clone "https://github.com/chriskohlhoff/asio" --depth 1 --branch asio-1-16-1 -q
      displayName: 'Install dependencies'
    - script: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_ZMQ=OFF -DWITH_OPENVR=OFF
        cmake --build .
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/bin'
        artifactName: binaries_linux
      displayName: 'Publish binaries'

  - job: macos1015
    pool:
      vmImage: 'macOS-10.15'
    displayName: 'MacOS 10.15'
    steps:
    - script: |
        sudo xcode-select -s /Applications/Xcode_12.3.app
      displayName: 'Setup Xcode'
    - script: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install glew glfw local/python2/python@2.7.17 libpng glm luajit libserialport libsndfile asio pkg-config
      displayName: 'Install dependencies'
    - script: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_ZMQ=OFF -DWITH_OPENVR=OFF
        cmake --build .
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/bin'
        artifactName: binaries_macos
      displayName: 'Publish binaries'

  - job: windows_x64
    pool:
      vmImage: 'vs2017-win2016'
    displayName: 'Windows VS2017 x86-64'
    steps:
    - script: |
        cd ref
        git clone "https://github.com/chriskohlhoff/asio" --depth 1 --branch asio-1-12-2 -q
      displayName: 'Download extra dependencies'
    - script: |
        mkdir build
        cd build
        cmake .. -A x64
        cmake --build . --config RelWithDebInfo
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/bin'
        artifactName: binaries_win64
      displayName: 'Publish binaries'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/pdb'
        artifactName: binaries_win64
      displayName: 'Publish symbols'

  - job: windows_x64_dbg
    pool:
      vmImage: 'vs2017-win2016'
    displayName: 'Windows VS2017 Debug'
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'shaders'
        artifactName: shaders
      displayName: 'Publish shaders'
    - script: |
        cd ref
        git clone "https://github.com/chriskohlhoff/asio" --depth 1 --branch asio-1-12-2 -q
      displayName: 'Download extra dependencies'
    - script: |
        mkdir build
        cd build
        cmake .. -A x64
        cmake --build . --config Debug
      displayName: 'Build'

  - job: windows_x32
    pool:
      vmImage: 'vs2017-win2016'
    displayName: 'Windows VS2017 x86'
    steps:
    - script: |
        cd ref
        git clone "https://github.com/chriskohlhoff/asio" --depth 1 --branch asio-1-12-2 -q
      displayName: 'Download extra dependencies'
    - script: |
        mkdir build
        cd build
        cmake .. -A Win32 -T v141_xp
        cmake --build . --config RelWithDebInfo
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/bin'
        artifactName: binaries_win32
      displayName: 'Publish binaries'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/pdb'
        artifactName: binaries_win32
      displayName: 'Publish symbols'
